exclude:
  - README.wiki
  - Capfile
  - config

url: http://hyip.github.io/info
name: The HYIP Project

path: /parser/site
permalink: /:categories/:title/

disqus_shortname: restcookbook
google_analytics: UA-53222355-1
