permalink: /:categories/:title/
exclude:
  - README.wiki
  - Capfile
  - config

url: http://hyip.github.io
name: The HYIP Project
topic: Site Ratings

disqus_shortname: hyips
google_analytics: UA-53222355-1
