permalink: /:categories/:title/
exclude:
  - README.wiki
  - Capfile
  - config

url: http://hyip.github.io
name: The HYIP Project
topic: Site Rating
path: /rating/site

disqus_shortname: tophyips
google_analytics: UA-53222355-1
